### PR TITLE
Some fixes for MinGW-w64 compatibility

### PR DESCRIPTION
**Pull request by silvioprog**

### CODE REVIEW

**Comment by silvioprog** [comment]
Sorry, but is there any special reason to not accept small fixes? Anyway, a comment at CORE-5682 showed me that MSVC 2013 is the current official building system for Windows, so I'm going to leave autotools for a while because it seems no longer maintained for MinGW.

**Comment by silvioprog** [comment]
I forgot an info. I've tried to build FB with MSVC 2017 (I've commented at CORE-5682), so I'm going to try on that again. Do you know how daily setups for Windows are generated?

**Comment by mariuz** [comment]
Seems that MINGW64 is supported in Visual Studio 

https://blogs.msdn.microsoft.com/vcblog/2017/07/19/using-mingw-and-cygwin-with-visual-cpp-and-open-folder/

**Comment by asfernandes** [comment]
As I understood patch was not for a full build and nobody merged it.

**Pull request closed without merging**
