### PR TITLE
SHA2 Refactoring [B3_0].

### PR DESCRIPTION
**Pull request by ghost**
General normalization of class structures.

### CODE REVIEW

**Comment by ibprovider** [comment]
I vote to remove test code from sha2.h(cpp).

1. They will saved in git history.
2. IBProvider tests has the verifications for SRP224-SRP512
3. I think, Jaybird also has these verification

Of course, in future these tests need restore in normal module test for FB source code.

**Comment by ibprovider** [comment]
get_BlockSize methods does not used in code.

Can I remove they?

**Comment by AlexPeshkoff** [comment]
Certainly - please do remove unused code

**Comment by ibprovider** [comment]
Hello,

I builded Firebird with these changes and test again (SRP224-SRP512) - all works as expected.

What about removing of garbage (test) from sha2.h(cpp)?

It will allows create more clean code.

**Pull request merged**
