### PR TITLE
Bug fix for CORE-5074 [B3_0]

### PR DESCRIPTION
**Pull request by ghost**
http://tracker.firebirdsql.org/browse/CORE-5074

TODO:
 - Unificated implementation for MAKE_desc_from_field and MAKE_desc_from_element functions.

### CODE REVIEW

**Comment by ibprovider** [comment]
Hello,

At current time - patch for B3_0_Release only.

I may create for master, but without tests on my side.

**Comment by dmitry-lipetsk** [comment]
Is anybody home?

**Comment by dyemanov** [comment]
Please commit the suggested unification to this PR and I'll merge it.

**Comment by dmitry-lipetsk** [comment]
Ok, within current day. Thanks.

**Comment by dmitry-lipetsk** [comment]
Another variant for declaration of function with common implementation:

```c++
static void MAKE_desc_from_field
				(dsc*                            const desc,
				 decltype(dsql_fld::dtype)       const field_dtype,
				 decltype(dsql_fld::scale)       const field_scale,
				 decltype(dsql_fld::subType)     const field_subType,
				 decltype(dsql_fld::length)      const field_length,
				 decltype(dsql_fld::flags)       const field_flags,
				 const decltype(dsql_fld::charSetId)&  field_charSetId,
				 decltype(dsql_fld::collationId) const field_collationId)

```
If you are want - I may change to this declaration.

**Comment by dmitry-lipetsk** [comment]
And?

**Comment by dyemanov** [comment]
I will front-port it to master myself, after some minor refactoring.

**Comment by dmitry-lipetsk** [comment]
Thanks,

> I will front-port it to master myself, after some minor refactoring.

No problem, FB2.5 will be patched? I may prepare PR for B2_5.

**Comment by dyemanov** [comment]
I'm patching v2.5 now. v2.5.9 is likely to be tagged for release tonight, so please review my commit.

**Comment by PizzaProgram** [comment]
Please do ! NOT ! use version numbering v2.5.9, but:
2.5.81
2.5.82
... or ...
2.5.901
2.5.902
...
You have promised before!
[CORE-5714](http://tracker.firebirdsql.org/browse/CORE-5714)

**Comment by dyemanov** [comment]
As I said before, 2.5.9 is the last sub-release and 2.5.10 will never happen. CORE-5714 is closed as rejected.

**Pull request merged**
