### PR TITLE
[cmake] Try to make it work again

### PR DESCRIPTION
**Pull request by raedrizqie**

### CODE REVIEW

**Comment by raedrizqie** [comment]
seems like nobody is interested with this.. closing..

**Comment by mariuz** [comment]
@raedrizqie please reopen i will test it :)

**Review by mariuz — COMMENTED** [review]
looks ok at first view

**Review by mariuz — COMMENTED** [review]
no changes

**Comment by raedrizqie** [comment]
i will reopen it

**Comment by aafemt** [comment]
Don't be too nervous. Firebird core team guys work on their own tasks. There is nobody to review and accept pull requests. But still from time to time they are reviewed. Just let it hang here for a year or two.

**Comment by raedrizqie** [comment]
I had recreated the cmake branch.. is there any way i can reopen using this same PR, or should i open a new PR?

**Comment by AlexPeshkoff** [comment]
Create a new one - will take a look at it.

**Comment by raedrizqie** [comment]
The new PR is here: #8201 . thanks

**Pull request closed without merging**
