### PR TITLE
Add window functions, PERCENT_RANK(), CUME_DIST() and NTILE().

### PR DESCRIPTION
**Pull request by nakagami**
- PERCENT_RANK http://tracker.firebirdsql.org/browse/CORE-3616
- CUME_DIST http://tracker.firebirdsql.org/browse/CORE-3617
- NTILE http://tracker.firebirdsql.org/browse/CORE-3618

### CODE REVIEW

**Comment by asfernandes** [comment]
@nakagami I believe it's better to add recordCount to SlidingWindow instead of pass it as win_row_count in winPass method. Next we may see if we can pass SlidingWindow in aggExecute too. Can you please do the first change?

**Comment by asfernandes** [comment]
@nakagami please let the structure changes for me. But your functions are producing different results than Oracle and PgSQL. Please see this:

```
create table t (n1 integer);

insert into t values (1);
insert into t values (2);
insert into t values (2);
insert into t values (3);

select n1,
       rank() over (partition by n1 order by n1) r,
       dense_rank() over (partition by n1 order by n1) dr,
       percent_rank() over (partition by n1 order by n1) pr,
       cume_dist() over (partition by n1 order by n1) cd,
       ntile(3) over (partition by n1 order by n1) nt
  from t
  order by n1;

```
Oracle / PgSQL:

```
1	1	1	0	1	1
2	1	1	0	1	1
2	1	1	0	1	2
3	1	1	0	1	1
```

Firebird:

```
           1                     1                     1       0.000000000000000      0.2500000000000000                     1
           2                     1                     1       0.000000000000000      0.5000000000000000                     1
           2                     1                     1       0.000000000000000      0.5000000000000000                     1
           3                     1                     1       0.000000000000000      0.2500000000000000                     1

```

**Comment by nakagami** [comment]
Sorry I don't have enogh time now. But I will see this issue. Please wait

**Comment by asfernandes** [comment]
I committed this pull request with many changes to fix the mentioned bugs. Please test it.

**Comment by nakagami** [comment]
Oh, Sorry and thank you so much !

**Pull request merged**
