### PR TITLE
autoconf: Define AMD64 for x86_64-w64-mingw32 target.

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
One question. Here I follow other `case...esac` statements. Shouldn't the `$target` be checked if the project is cross compiled?

**Comment by AlexPeshkoff** [comment]
We usually accept porting activity. I reject this pull request for one and only one reason - please first complete that port, afterwards your pull request will be accepted.

**Comment by Biswa96** [comment]
Is there any way I can contact any developer for little y/n questions without creating any account in another website?

**Comment by AlexPeshkoff** [comment]
For discussion among Firebird Developers 
***@***.***>

**Comment by AlexPeshkoff** [comment]
Sorry, looks like GH kills email addresses.

firebird-devel
lists
sourceforge
net

**Pull request closed without merging**
