### PR TITLE
Fix invariants optimization involving views (#7388)

### PR DESCRIPTION
**Pull request by dyemanov**
The idea is that we should not compare view field's stream with streams from other RSEs until the field has been expanded to the proper expression. Once it's done, `sub->pass1()` will recursively take care of the invariant checking. The test case from #7388 now shows good performance in both cases, but I'd like to have a second opinion.

### CODE REVIEW

**Comment by livius2** [comment]
Is it possible to see difference of such execution in explain plan? 
As now both plans are equal. Do you consider some extension to it?

**Comment by dyemanov** [comment]
I agree it could be useful. Will take look at possible implementation.

**Comment by dyemanov** [comment]
This is the suggested plan output:

```
Sub-query (invariant)
    -> Singularity Check
        -> Aggregate
            -> Nested Loop Join (outer)
                -> Filter
                    -> Hash Join (inner)
                        -> Table "RDB$RELATION_FIELDS" as "SUB RF" Full Scan
                        -> Record Buffer (record length: 529)
                            -> Table "RDB$RELATIONS" as "SUB R" Full Scan
                -> Filter
                    -> Table "RDB$SECURITY_CLASSES" as "SUB SC" Access By ID
                        -> Bitmap
                            -> Index "RDB$INDEX_7" Unique Scan
Select Expression
    -> Filter
        -> Nested Loop Join (outer)
            -> Nested Loop Join (inner)
                -> Filter
                    -> Table "RDB$RELATIONS" as "SUB R" Access By ID
                        -> Bitmap
                            -> Index "RDB$INDEX_1" Range Scan (full match)
                -> Filter
                    -> Table "RDB$RELATION_FIELDS" as "SUB RF" Access By ID
                        -> Bitmap
                            -> Index "RDB$INDEX_4" Range Scan (full match)
            -> Filter
                -> Table "RDB$SECURITY_CLASSES" as "SUB SC" Access By ID
                    -> Bitmap
                        -> Index "RDB$INDEX_7" Unique Scan

```

**Comment by livius2** [comment]
Will be good to see both plans in new version. 
Or it will be now like this?

```
Sub-query (invariant)
    -> Singularity Check
```

and second version

```
Select Expression
    -> Singularity Check
```

or it will look differently?


```
Sub-query (invariant)
    -> Singularity Check
```

and second version

```
Sub-query (variant)
    -> Singularity Check
```

**Comment by dyemanov** [comment]
`"Select Expression"` is the main query, it does not change. For sub-query now we see also `"Select Expression"`, after the patch it will look as either `"Sub-query"` or `"Sub-query (invariant)"`.

**Comment by dyemanov** [comment]
Most sub-queries are correlated in practice, so reporting them as "variant" IMO is about to cause more questions than keeping is simple.

**Comment by livius2** [comment]
Yes, may concern was only if for variant there will be `Select Expression` or also `Sub-query` :)

**Comment by dyemanov** [comment]
Plan explain improvements will be applied separately.

**Pull request merged**
