### PR TITLE
Example of shutting database down

### PR DESCRIPTION
**Pull request by aafemt**
And fix of a couple of mistypes.

### CODE REVIEW

**Comment by AlexPeshkoff** [comment]
I'm not sure - do we need so much almost same samples that differ only in a few bytes in SPB?
May be better collect them in one?

**Comment by aafemt** [comment]
May be. I use these examples to test single pieces of engine, so they must be narrow for 
this purpose. You can combine them into super-example if you wish.

**Comment by AlexPeshkoff** [comment]
I've fixed comments in separate commit.
BTW, what prevents from using fbsvcmgr for engine tests? Re.services old/new API gate performs minimum (more precise - no) actions.

**Comment by aafemt** [comment]
To use fbsvcmgr for tests I would have to make it understand unicode first.

**Pull request closed without merging**
