### PR TITLE
CORE-5746: Remove the restriction on create/delete, enable/disable user indexes in the system tables

### PR DESCRIPTION
**Pull request by abzalov**

### CODE REVIEW

**Review by hvlad — APPROVED** [review]
I see no problems. If there will be no objections from others, i'll merge this pr (as well as pr156)

**Comment by asfernandes** [comment]
I have this error when trying to create an index:

```sql
SQL> create index i1 on rdb$relations (rdb$relation_name);
Statement failed, SQLSTATE = 28000
unsuccessful metadata update
-CREATE INDEX I1 failed
-no permission for ALTER access to TABLE RDB$RELATIONS
```

**Comment by abzalov** [comment]
Oops, I forgot merge changes to the master branch for method CreateIndexNode::checkPermission - SCL_check_relation(..., false).
I'll fix it now.

**Comment by hvlad** [comment]
I checked B3_0_Release branch only before the merge, don't worry - i'll update master

**Comment by abzalov** [comment]
Thanks!

**Pull request merged**
