### PR TITLE
Reorganization of code to reduce the number of compiler warnings (VC++) [B3_0]

### PR DESCRIPTION
**Pull request by ghost**
Example of warnings:
 alloc.h(292): warning C4595: 'operator new': non-member operator new or delete functions may not be declared inline
 alloc.h(296): warning C4595: 'operator new[]': non-member operator new or delete functions may not be declared inline
 alloc.h(310): warning C4595: 'operator delete': non-member operator new or delete functions may not be declared inline
 alloc.h(314): warning C4595: 'operator delete[]': non-member operator new or delete functions may not be declared inline

### CODE REVIEW

**Comment by AlexPeshkoff** [comment]
That changes are already present in HEAD, as for me I see no big reasons to apply them to FB3. At least Mac build should be checked with them in order not to break it.

**Comment by ibprovider** [comment]
I asked to make these changes (in FB3) three or four years ago.

**Comment by hvlad** [comment]
Sorry for been too late, @AlexPeshkoff - we still have a LOT of this warnings in DEBUG build:

>fb40\src\remote\../common/classes/alloc.h(404): warning C4595: 'operator delete': non-member operator new or delete functions may not be declared inline (compiling source file ..\..\..\src\remote\inet.cpp)

>fb40\src\remote\../common/classes/alloc.h(408): warning C4595: 'operator delete[]': non-member operator new or delete functions may not be declared inline (compiling source file ..\..\..\src\remote\inet.cpp)

**Comment by AlexPeshkoff** [comment]
Vlad, I do not see big reasons to deal with warnings in non-HEAD branches. On the other hand I have no problems if you fix them. Mac build is always checked now i.e. this problem can be easily solved.

**Comment by hvlad** [comment]
Sorry again, did not notice it was about v3. But I talked about the master

**Comment by AlexPeshkoff** [comment]
In master it's fixed

**Comment by hvlad** [comment]
Please, read **compiler** messages above. DEBUG build is still not fixed

**Comment by AlexPeshkoff** [comment]
Vlad, I see that messages. But I do not understand - why they begin just from line 404, not earlier? Or may be the sample is incomplete?

**Comment by hvlad** [comment]
```
#ifdef DEBUG_GDS_ALLOC

#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Winline-new-delete"
#endif

inline void operator delete(void* mem) FB_NOTHROW
{
	MemoryPool::globalFree(mem);
}
inline void operator delete[](void* mem) FB_NOTHROW
{
	MemoryPool::globalFree(mem);
}

#ifdef __clang__
#pragma clang diagnostic pop
#endif

#endif // DEBUG_GDS_ALLOC

```
You see - there are two inline operators left. I tried to comment it out and build is OK.

**Comment by AlexPeshkoff** [comment]
Take a look at the code 30 lines before this.
Why no warnings on that inlines?

**Comment by AlexPeshkoff** [comment]
Feel free to convert them to extern with body in alloc.cpp.

**Comment by hvlad** [comment]
Done

**Pull request closed without merging**
