### PR TITLE
This should fix QA tests core_4418 and core_6044

### PR DESCRIPTION
**Pull request by aafemt**
...but may break any other that check isql output for procedure and function parameters.

### CODE REVIEW

**Comment by aafemt** [comment]
Field B. In your output it is as expected by the tests. In my comment it is shorter (though semantically the same).

**Comment by AlexPeshkoff** [comment]
I.e. p/r restores legacy behavior with output of DB default charset - right? In that case what test can be broken by THIS p/r?

**Comment by sim1984** [comment]
Maybe the tests should still be rewritten for the correct output, rather than trying to restore the passing of these tests?

**Comment by dyemanov** [comment]
> Maybe the tests should still be rewritten for the correct output, rather than trying to restore the passing of these tests?

Maybe, we just need to agree what is a correct output ;-)

**Comment by aafemt** [comment]
> I.e. p/r restores legacy behavior with output of DB default charset - right? In that case what test can be broken by THIS p/r?

It depends on how deeply you count "legacy behavior". This PR probably restores behavior of v4 but I'm not sure.

What I said that may be broken is following script:
`create procedure p(A varchar(20) collate UTF8) as begin end; show procedure p;`
In contrast to the table above it will show collation without charset for the parameter. It can be fixed too but not so simple.

**Comment by dyemanov** [comment]
Personally, I prefer `isql -x` to generate as simplified script as possible. So omitting the character set which matches the database default character set looks like a good idea. But I'm not so sure about the `SHOW` command, where IMHO it makes sense to print the detailed definition, thus avoiding the need to run `SHOW DATABASE` to understand the real charset of the shown object(s).

**Comment by AlexPeshkoff** [comment]
Agree with @dyemanov, just want to add that in a case we have to choose between simplified script and detailed SHOW information - I prefer the second, script getting a little longer will never hurt, not understood by user SHOW result is much worse.

**Comment by aafemt** [comment]
I see the point. In this case you can simply merge this PR and see if any other QA test fail. If there will be any - I'll do more adjustments.

**Pull request merged**
