### PR TITLE
Raised API version because of changes related to #6886

### PR DESCRIPTION
**Pull request by aafemt**

### CODE REVIEW

**Comment by AlexPeshkoff** [comment]
Dmitry & Vlad!
I'm not sure - is it correct reason to change FB_API_VER ?

**Review by hvlad — COMMENTED** [review]
Since I see no usage of FB_API_VER in Firebird code, I'd say we need to define a rules first.
Every interface supports own versioning and FB_API_VER gives nothing to this, IMHO.
Perhaps FB_API_VER should be changed after massive changes in interfaces. And #6886 could be such a case. Lets define rules first. 
What is main purpose of FB_API_VER ? 
How it should be used by end-users ?

**Comment by aafemt** [comment]
I would use it like this:
```
void ODBCAttachment::detach(Firebird::CheckStatusWrapper* status)
{
    internalDetach(status);
#if FB_API_VER > 40
   release();
#endif
}
```
```
#if FB_API_VER > 40
void ODBCAttachment::deprecatedDetach(Firebird::CheckStatusWrapper* status)
{
    internalDetach(status);
}
#endif
```

**Comment by asfernandes** [comment]
We can also make cloop generate per-interface `#define` version, instead of only C++ const.

**Comment by AlexPeshkoff** [comment]
Generating preprocessor constant together with C++ one seems logical. At least much better than artificial FB_API_VER.

**Pull request closed without merging**
