### PR TITLE
Use hard links instead of soft links

### PR DESCRIPTION
**Pull request by aafemt**
I've found that they works even without elevated privileges

### CODE REVIEW

**Comment by aafemt** [comment]
Perhaps it may be a solution as well. But what is wrong with hard links for those who are not aware of Developers Mode?

**Comment by hvlad** [comment]
I hardly see someone not in Dev mode trying to build Firebird (or anything).
As for "problem" with hard links - for cleanup it requires to delete both file and a link, AFAIU.
This could add some unexpected confusion for non-linux people.

PS IMHO, the real root of this issue is that some our .epp files historycally uses not original database names but symlinks to it.

**Comment by aafemt** [comment]
Softlinks on Windows are deleted automatically if original file is deleted? That's a shocking surprise.

**Comment by hvlad** [comment]
Softlink doesn't preserve original file.
Thanks for patience ;)

**Comment by aafemt** [comment]
Ah, this way. I see.

**Pull request closed without merging**
