### PR TITLE
[FB4, GBAK] Correct handling of NULLs in RDB$RETURN_ARGUMENT and RDB$ARGUMENT_POSITION

### PR DESCRIPTION
**Pull request by dmitry-lipetsk**
This is a fix for issue #7869 - a potential problem of writing into database the uninitialized value in RDB$RETURN_ARGUMENT and RDB$ARGUMENT_POSITION columns.

Of course, GBAK has a lot of equal problems for other columns but I want to fix a problem only with these ones.

UPD1. Symmetric problem in backup is fixed. Thanks to Adriano.

### CODE REVIEW

**Comment by aafemt** [comment]
I'm still sure that fld_f_position must be not nullable to prevent UB in engine.

**Comment by dmitry-lipetsk** [comment]
> I'm still sure that fld_f_position must be not nullable to prevent UB in engine.

Me too but it is a change of ODS and I am too young to ask and suggest such changes.

**Comment by aafemt** [comment]
Is it really an ODS change? No field added or deleted, no even unique index/constraint put here (though one won't hurt). Old code should work with new definition flawlessly and vice versa.

**Comment by asfernandes** [comment]
In real life, this looks like more as a code improvement, and a partial one.
Why PR against v4 instead only master?

**Comment by dmitry-lipetsk** [comment]
> In real life, this looks like more as a code improvement, and a partial one. Why PR against v4 instead only master?

I can added these changes to master and fb5, too.

I want to add these changes to FB4, because I work with this version and they are needed to fix another problem with UDF SCALAR-array arguments (#7846, #7845)

**Comment by dmitry-lipetsk** [comment]
Hello. Please, let me know if I must create equal PR for FB5 and master.  It is not a problem for me. Thanks.

**Pull request merged**
