### PR TITLE
[FB4] New OO-API example for restoring a database through server service.

### PR DESCRIPTION
**Pull request by dmitry-lipetsk**
This example is based on one for backuping database through service created by Alexander Peshkoff.

### CODE REVIEW

**Comment by AlexPeshkoff** [comment]
Certainly adding more examples is good. But I'm not sure - is it really worth to have examples that differ in 6 (six) lines only, 2 of them being comments and 1 - printf() with example name?

**Comment by dmitry-lipetsk** [comment]
It can save the time for anyone who want to learn only restore.

**Review by dyemanov — APPROVED** [review]

**Comment by dyemanov** [comment]
New file should be mentioned in `examples/readme`

**Comment by dmitry-lipetsk** [comment]
> New file should be mentioned in `examples/readme`

Done.

**Pull request merged**
