### PR TITLE
Fix time "shift" with time zone by converting it to UTC in CAST FORMAT #2388

### PR DESCRIPTION
**Pull request by TreeHunter9**

### CODE REVIEW

**Comment by asfernandes** [comment]
There seems to still have incorrect cases:

```
SQL> select cast('2023-11-03 12:00 -04:00' as timestamp format 'YYYY-MM-DD HH24:MI TZH:TZM' ) from rdb$database;

                     CAST 
========================= 
2023-11-03 12:00:00.0000  

SQL> select cast('2023-11-03 12:00 -06:00' as timestamp format 'YYYY-MM-DD HH24:MI TZH:TZM' ) from rdb$database;

                     CAST 
========================= 
2023-11-03 12:00:00.0000  
```

```
SQL> select cast('12 -04:00' as time without time zone format 'HH24 TZH:TZM' ) from rdb$database;

         CAST 
============= 
12:00:00.0000 

SQL> select cast('12 -06:00' as time without time zone format 'HH24 TZH:TZM' ) from rdb$database;

         CAST 
============= 
12:00:00.0000 
```

**Comment by TreeHunter9** [comment]
I did it on purpose. I thought if we specify time without time zone, time zone will be ignored. If it's incorrect behavior, I will fix it.

A little off topic, I guess default conversion have some issues too with time zones:
```
SQL> SELECT CAST('12:30:15.1234 +03:30' AS TIME WITHOUT TIME ZONE) FROM RDB$DATABASE;

CAST 
============= 
12:00:15.1234

SQL> SELECT CAST('12:30:15.1234 -03:30' AS TIME WITHOUT TIME ZONE) FROM RDB$DATABASE;

CAST 
============= 
19:00:15.1234
```

**Comment by asfernandes** [comment]
> A little off topic, I guess default conversion have some issues too with time zones:

Looks correct for me. My time zone is -03:00:

```
SQL> SELECT CAST('12:30:15.1234 +03:30' AS TIME WITHOUT TIME ZONE) FROM RDB$DATABASE;

         CAST 
============= 
06:00:15.1234 

SQL> SELECT CAST('12:30:15.1234 -03:30' AS TIME WITHOUT TIME ZONE) FROM RDB$DATABASE;

         CAST 
============= 
13:00:15.1234 
```

What's your time zone?

**Comment by asfernandes** [comment]
> A little off topic, I guess default conversion have some issues too with time zones:

Looks like you are on +03:00? Then I'd say it's correct.

Then I'd say the script I send is not consistent with this behavior.

**Comment by TreeHunter9** [comment]
> Looks like you are on +03:00?

Correct.

**Comment by asfernandes** [comment]
@TreeHunter9 are you going to fix the cases I mentioned in this PR?

**Comment by TreeHunter9** [comment]
Yes, I am on a little vacation right now and away from my work PC.

**Comment by pavel-zotov** [comment]
It seems that 'RM' (abbreviation for Roman numbers) can not be used for cast from string to date in '\<cast template\>':
```
set heading off;
set echo on;

-- date.time to string:
select cast(current_date as varchar(50) format 'DD.RM.YYYY') from rdb$database;

-- string to date/time:
select cast('24.XI.2023' as date format 'DD.RM.YYYY') from rdb$database;
```

Output:
```
-- date.time to string:
select cast(current_date as varchar(50) format 'DD.RM.YYYY') from rdb$database;
24.XI.2023

-- string to date/time:
select cast('24.XI.2023' as date format 'DD.RM.YYYY') from rdb$database;

Statement failed, SQLSTATE = HY000
Value for RM pattern is out of range [1, 12]
```

**Pull request merged**
