### PR TITLE
CORE-5710 make precision optional for DECFLOAT

### PR DESCRIPTION
**Pull request by mrotteveel**
Fixes [CORE-5710](http://tracker.firebirdsql.org/browse/CORE-5710)

This commit increases the number of reduce/reduce conflicts, but I couldn't find a way to fix that.

### CODE REVIEW

**Comment by AlexPeshkoff** [comment]
Well - you've noticed it. That's the only reason why I've removed this feature from initial implementation. Such huge growth of conflicts is definitely not good and presence of default precision is not worth it.

**Comment by asfernandes** [comment]
Was this conflicts investigated, i.e., FLOAT and DECIMAL uses the same kind of construction. Are they also adding conflicts? Or is it because DECFLOAT is not a reserved word?

**Comment by dyemanov** [comment]
Given that DECFLOAT is a standard datatype, I suppose we need to define this token as a reserved word.

**Comment by AlexPeshkoff** [comment]
On 03/26/18 13:50, Dmitry Yemanov wrote:
>
> Given that DECFLOAT is a standard datatype, I suppose we need to 
> define this token as a reserved word.
>

This is the simplest solution (and probably long-term correct one). But 
we all remember problems people had when we declared some words reserved.

**Comment by AlexPeshkoff** [comment]
On 03/26/18 13:45, Adriano dos Santos Fernandes wrote:
>
> Was this conflicts investigated, i.e., FLOAT and DECIMAL uses the same 
> kind of construction. Are they also adding conflicts? Or is it because 
> DECFLOAT is not a reserved word?
>

That's because it's not a reserved word. Conflicts happens with words 
also used in column declararations like CHECK, COLLATE, UNIQUE, 
GENERATED, etc.

**Comment by mrotteveel** [comment]
Removing `DECFLOAT` from the `non_reserved_word` reverts the reduce/reduce conflicts back to 17. Personally I don't think it is a problem to make it reserved. I would guess (and hope) this isn't a name that would come up by itself in a normal database. It is also specified in SQL:2016 as a reserved word. Shall I commit my change?

**Comment by AlexPeshkoff** [comment]
On 03/26/18 16:33, Mark Rotteveel wrote:
>
> Removing |DECFLOAT| from the |non_reserved_word| reverts the 
> reduce/reduce conflicts back to 17. Personally I don't think it is a 
> problem to make it reserved. I would guess (and hope) this isn't a 
> name that would come up by itself in a normal database. It is also 
> specified in SQL:2016 as a reserved word. Shall I commit my change?
>

yes

**Comment by mrotteveel** [comment]
Added to `keyword_or_column`

**Pull request merged**
