### PR TITLE
Use restricted list of C++11 features

### PR DESCRIPTION
**Pull request by asfernandes**

### CODE REVIEW

**Comment by asfernandes** [comment]
@dyemanov what about merge this pull request?

**Comment by AlexPeshkoff** [comment]
On 21.09.2016 18:46, Adriano dos Santos Fernandes wrote:
> @dyemanov what about merge this pull request?
>

With what compilers did you try it ?

**Comment by hvlad** [comment]
IIRC, snapshot build for Windows still produced using VC10 (VS2010). I doubt it supports all features in this branch.

**Comment by dyemanov** [comment]
@hvlad, snapshots are built using MSVC13.

**Comment by asfernandes** [comment]
@AlexPeshkoff clang++ 3.8.0, g++ 5.4.0 and MSVC 14.

**Comment by dyemanov** [comment]
Compiles fine with MSVC2013, does not compile with MSVC10. More or less as expected.

**Comment by aafemt** [comment]
How about GCC 4.7-4.9? Not all distros already include 5.x.

**Comment by asfernandes** [comment]
No distro includes FB 4.

**Comment by aafemt** [comment]
That's why it must be able to be built from sources with existing compiler.

**Comment by hvlad** [comment]
> snapshots are built using MSVC13.
Very good :) No objection from my side

**Comment by AlexPeshkoff** [comment]
Should better work with at least gcc 4.9. It's compiler used in current stable gentoo.
# gcc --version
gcc (Gentoo 4.9.3 p1.4, pie-0.6.4) 4.9.3

**Comment by asfernandes** [comment]
@AlexPeshkoff can you test it then?

**Comment by dyemanov** [comment]
Tested with gcc 4.8.2, the branch compiles fine.

**Comment by AlexPeshkoff** [comment]
With 4.9.3 it alsi builds fine.
I think it's time to merge it.

**Comment by aafemt** [comment]
> I think it's time to merge it.


If you have time, merge PR #15 first.

**Pull request merged**
