### PR TITLE
Fix crash on external engine trigger executing for transaction triggers

### PR DESCRIPTION
**Pull request by artyom-smirnov**
trg->relation can be null, so need checking

### CODE REVIEW

**Comment by artyom-smirnov** [comment]
Found this bug when working with fbjava. I've have fixed it straightforward, but may be better solution, exists.

**Comment by artyom-smirnov** [comment]
Also same crash in 3.0 branch

**Comment by AlexPeshkoff** [comment]
Your fix is OK - please provide fix for 3.0 too

**Comment by artyom-smirnov** [comment]
My mistake, 3.0 branch not affected, we had crash in Red Database 3.0 because of 4.0 backported code.

**Pull request merged**
